import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      
      <body
       className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <img src="/hh.PNG" alt="Handcrafter's Haven Logo" />
          <h1>Handcrafter's Haven</h1>
          <nav>
            <a href="/" className="button">Home</a>
            <a href="/products" className="button">Products</a>
            <a href="/account" className="button">Account</a>
            <a href="/cart" className="button">Cart</a>
          </nav>
        </header>
        {children}
      <footer>
        <p>© 2025 Handcrafter's Haven. This is a school website.</p>
      </footer>
      </body>
      
    </html>
  );
}
